### ISSUE TITLE
Docker: HTTPS upgrade issues

### ISSUE THREAD

**Issue by sNiXx** [OWASP/threat-dragon#1137]
**Describe the bug**:
When running the application in a Docker environment, the container comes up, but when visiting the URL, the page stays blank. Using developer tools, I can see several errors (also see screenshots below) that are related to attempts to upgrade to https.

I was eventually able to figure out how to run a container using docker compose, but I think the documentation could be improved here. This was quite a frustrating experience to be honest :cry: 

**Expected behaviour**:
I expect the page to show the Threat Dragon dashboard.

**Environment**:

- Version: 2.3.0 (also tried 2.2.0)
- Platform: Web App
- OS: Linux
- Browser: Firefox, Brave

**To Reproduce**:
Run the container with the following compose file and .env file (secrets removed)

docker-compose.yml
```
services:
  threatdragon:
    image: owasp/threat-dragon:v2.3.0
    container_name: threatdragon
    ports:
      - 8060:3000
    restart: always
    env_file: threatdragon.env
```

.env
```
NODE_ENV=development
SERVER_API_PROTOCOL=http
LOG_LEVEL=debug
ENCRYPTION_KEYS='[{"isPrimary": true, "id": 0, "value": "somekey1"}]'
ENCRYPTION_JWT_SIGNING_KEY=somekey2
ENCRYPTION_JWT_REFRESH_SIGNING_KEY=somekey3
```

command:
```
docker compose -f threatdragon_docker-compose.yml --env-file threatdragon.env up
```

**Any additional context, screenshots, etc**:
![TD001](https://github.com/user-attachments/assets/ed3adc49-7c4b-402f-b85c-1f595ccf28b8)

![TD002](https://github.com/user-attachments/assets/47c5df82-3721-43e0-8613-78579f7f97a1)
