### ISSUE TITLE
CI: possible expired token for docker deploy

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#434]
**Describe the bug**
during the build_docker_image action of the deploy workflow we get error:
```
Run docker/login-action@v1
Error: Username and password required
```
**Expected behaviour**
it seems that the username + token is no longer accepted from `deploy.yaml`:
```
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

**Environment**
 - Version: 2.0
 - Platform: any
 - OS: any
 - Browser: any

**To Reproduce**
rerun build_docker_image action

**Any additional context, screenshots, etc**
