### ISSUE TITLE
Docker hub login failing

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#470]
**Describe the bug**
The build_docker_image pipeline job fails at the Login to Docker Hub stage:

```
0s
Run docker/login-action@v1
  with:
    ecr: auto
    logout: true
  env:
    image_name: threatdragon/owasp-threat-dragon:1efb63a4b1c930775770c5a59180e12f9ae733a8
Error: Username and password required
```

**Expected behaviour**
This is the yaml code

```
     - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

probably the DOCKERHUB_TOKEN needs refreshing?

**Environment**
 - Version: main branch
 - Platform: any
 - OS: any
 - Browser: any

**To Reproduce**
See pipeline results: https://github.com/OWASP/threat-dragon/runs/7687274812?check_suite_focus=true

**Any additional context, screenshots, etc**
<img width="736" alt="Screenshot 2022-08-05 at 10 42 52" src="https://user-images.githubusercontent.com/29352392/183050892-b503f593-8b4c-447d-a03b-cd58d850f420.png">
