### ISSUE TITLE
Some GitHub Actions jobs should be conditional  

### ISSUE THREAD

**Issue by ChristopherHackett** [OWASP/threat-dragon#616]
**Describe the bug**
Today I synced a fork of this project. I'm unsure if I had previously enabled GitHub Actions on the fork or if recent changes in the upstream repo caused it to be enabled. However after syncing I got a two notifications of failure of jobs and workflows that should only berun from the main repo IMO 

**Expected behaviour**
Jobs should be skipped
* Deploy to Heroku
  ** ALL Jobs here should really be skipped as I can't see the use of this workflow from other repos
* CI Pipeline
  ** `build docker image` and jobs dependent on it should be skipped  

The docs for GitHub Actions say `jobs.[job_id].if` can be used for this 
```
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
```
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository

**Environment**
n/a

**To Reproduce**
n/a

**Any additional context, screenshots, etc**
