### ISSUE TITLE
winget support would be great

### ISSUE THREAD

**Issue by exoosh** [OWASP/threat-dragon#848]
**Describe what problem your feature request solves**:

It would make the installation and upgrading the software on modern Windows very very easy.

**Describe the solution you'd like**:

I'd love to be able to say `winget install --id OWASP.ThreatDragon` or similar -- and of course subsequently `winget upgrade --id OWASP.ThreatDragon` -- in order to install and upgrade the software.

PS: I think there is a way to integrate this with GitHub automation, but I need to dig that up again and will comment once I find it. That way if the assets in your releases follow a particular schema a PR will automatically go to microsoft/winget-pkgs.

**Comment by exoosh** [comment]
Here's the automation option I had in mind: https://github.com/vedantmgoyal2009/winget-pkgs-automation

**Comment by jgadsden** [comment]
many thanks @exoosh , if you find out how to do it that would be great. I have assigned it to you, but decline if you want to

**Comment by assarbad** [comment]
So apparently `winget-releaser` is the way to go. And with Vim I have found a repo where this is done. So it can probably made to work for _this one_, too. See [here](https://github.com/vim/vim-win32-installer/blob/master/.github/workflows/winget_stable.yml).

Two things:

1. could you assign it to me (same guy as @exoosh) but my private account?
2. how long do I have until version 2.2?

**Comment by jgadsden** [comment]
Thanks @assarbad  /  @exoosh for taking this on. I have given you more permissions for this repo so you should be able to add labels and run tests, that sort of thing
Version 2.1.4 is out this week - version 2.2 sometime second quarter of this year

**Comment by exoosh** [comment]
I will test this first in a repo of my own just to make sure I get it right. Then will "port" it over here with a PR. In all likelihood there will be some secrets involved that need to be created for the PRs to be posted to `winget-pkgs`.

**Comment by jgadsden** [comment]
moveing this back to version 2.4 from version 2.3  - unless this is done @exoosh ? No problem either way

**Comment by jgadsden** [comment]
that sounds very good to me, thanks @exoosh , and agreed, just one asset and one architecture
I know next to nothing about Windows, so appreciate you taking this on
we can coordinate and when the release is created we can add the winget files / support

**Comment by exoosh** [comment]
Cool, alright. So to summarize: for the upcoming release I will create the manifest more or less manually and for subsequent ones the GitHub action should take over.

**Comment by assarbad** [comment]
@jgadsden I'm silly, sorry. We can do the WinGet manifest right now (and get automation in place for the upcoming version before it gets released), I'd just like to get your feedback on my choices for the data to be entered.

Please pay particular attention to the following fields below:

* `Publisher:`
* `PublisherUrl:`
* `PublisherSupportUrl:`
* `Author:`
* `LicenseUrl:`
* `Copyright:`
* `CopyrightUrl:`
* `ShortDescription:`
* `Description:`
* `ReleaseNotesUrl:`

Also note that some items are populated based on your project settings. E.g. the tags.

Created with Komac 2.6.0:
```
$ komac new OWASP.ThreatDragon --package-locale en-US --copyright 'Copyright © 2024 OWASP contributors (owasp.org)' --publisher 'OWASP/threat-dragon project' --publisher-url https://github.com/OWASP/threat-dragon/ --publisher-support-url https://github.com/OWASP/threat-dragon/issues/new/choose --package-name ThreatDragon --package-url https://github.com/OWASP/threat-dragon/releases --author 'OWASP contributors' --moniker threatdragon --license Apache-2.0 --license-url https://github.com/OWASP/threat-dragon/blob/main/license.txt --short-description 'OWASP Threat Dragon is a free, open-source, cross-platform threat modeling application. It is used to draw threat modeling diagrams and to list threats for elements in the diagram.' --description Description --release-notes-url https://github.com/OWASP/threat-dragon/releases/tag/v2.2.0 -v 2.2.0 -u https://github.com/OWASP/threat-dragon/releases/download/v2.2.0/Threat-Dragon-ng-Setup-2.2.0.exe
```

# Draft version of manifest files

In case I somehow don't respond, the following files ought to go under the name given in their subsection titles respectively into https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OWASP into a subdirectory `ThreatDragon`.

## `OWASP.ThreatDragon.installer.yaml`

```yaml
# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OWASP.ThreatDragon
PackageVersion: 2.2.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-02-17
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/OWASP/threat-dragon/releases/download/v2.2.0/Threat-Dragon-ng-Setup-2.2.0.exe
  InstallerSha256: D5295584C6EDBBFA8515218C173E9125ADD690D5DEDE37702FC0B7D7FDD5E93A
ManifestType: installer
ManifestVersion: 1.6.0
```

## `OWASP.ThreatDragon.locale.en-US.yaml`

NB: The `Description` field was added after the Komac invocation.

```yaml
# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: OWASP.ThreatDragon
PackageVersion: 2.2.0
PackageLocale: en-US
Publisher: OWASP Threat Dragon
PublisherUrl: https://github.com/OWASP/threat-dragon/
PublisherSupportUrl: https://github.com/OWASP/threat-dragon/issues/new/choose
Author: OWASP contributors
PackageName: Threat-Dragon-ng
PackageUrl: https://github.com/OWASP/threat-dragon/releases
License: Apache-2.0
LicenseUrl: https://github.com/OWASP/threat-dragon/blob/main/license.txt
Copyright: Copyright © 2024 OWASP Threat Dragon
CopyrightUrl: https://github.com/OWASP/threat-dragon
ShortDescription: OWASP Threat Dragon is a free, open-source, cross-platform threat modeling application. It is used to draw threat modeling diagrams and to list threats for elements in the diagram.
Description: |
    OWASP Threat Dragon is a free, open-source, cross-platform threat modeling application. It is used to draw threat modeling diagrams and to list threats for elements in the diagram. Mike Goodwin created Threat Dragon as an open source community project that provides an intuitive and accessible way to model threats.
    Threat Dragon is designed to be accessible for various types of teams, with an emphasis on flexibility and simplicity. It is an OWASP Lab Project and follows the values and principles of the threat modeling manifesto.
Moniker: threatdragon
Tags:
- owasp
- owasp-threat-dragon
- sdlc
- threat-dragon
- threat-modeling
ReleaseNotesUrl: https://github.com/OWASP/threat-dragon/releases/tag/v2.2.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
```

## `OWASP.ThreatDragon.yaml`

```yaml
# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: OWASP.ThreatDragon
PackageVersion: 2.2.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
```
