### ISSUE TITLE
Gitlab integration not working

### ISSUE THREAD

**Issue by fdellwing** [OWASP/threat-dragon#947]
**Describe the bug**:
I tried to setup Thread Dragon with Gitlab integration, but I don't get the button to use it. The documentation (https://owasp.org/www-project-threat-dragon/docs-2/development-environment/) does not help here.

**Expected behaviour**:
Having a working integration

**Environment**:

- Version: 2.2.0
- Platform: Web App
- OS: Linux (docker compose)
- Browser: Firefox

**To Reproduce**:

**Any additional context, screenshots, etc**:

```yaml
services:
  threatdragon:
    image: owasp/threat-dragon:stable
    ports:
      - 127.0.0.1:3000:3000
    environment:
      ENCRYPTION_KEYS: '[{"isPrimary": true, "id": 0, "value": "12345678"}]'
      ENCRYPTION_JWT_SIGNING_KEY: '12345678'
      ENCRYPTION_JWT_REFRESH_SIGNING_KEY: '12345678'
      SERVER_API_PROTOCOL: 'http'
      GITLAB_APPLICATION_ID: '994fa59201dad799c7292d56bbbd353650223bcabf9d1bce15c1a2731dd0d23d'
      GITLAB_APPLICATION_SECRET: 'gloas-12345678'
      GITLAB_REDIRECT_URI: 'https://td.foobar.com/api/oauth/return'
      GITLAB_ENTERPRISE_HOSTNAME: 'gitlab.foobar.com'
```

![grafik](https://github.com/OWASP/threat-dragon/assets/22813377/9bdf4ddc-0fde-40fd-b8bd-1b32e7143598)
 
![grafik](https://github.com/OWASP/threat-dragon/assets/22813377/c9c83b4f-d05b-42b3-bcda-229986c5d29a)
